
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class Frame1 extends javax.swing.JFrame {
    String temp = "";
    Double ti, bt, h1;

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bb = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        rbp = new javax.swing.JRadioButton();
        rbl = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bkeluar = new javax.swing.JButton();
        bhitung = new javax.swing.JButton();
        bcl = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Utsaah", 1, 24)); // NOI18N
        jLabel1.setText("UJI IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 170, 30);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setText("Berat Badan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 140, 90, 40);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel3.setText("Jenis Kelamin");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 180, 90, 40);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 100, 90, 40);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 60, 90, 40);
        getContentPane().add(bb);
        bb.setBounds(180, 150, 60, 30);

        tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiActionPerformed(evt);
            }
        });
        getContentPane().add(tinggi);
        tinggi.setBounds(180, 110, 60, 30);
        getContentPane().add(nama);
        nama.setBounds(180, 70, 140, 30);

        bg.add(rbp);
        rbp.setText("Perempuan");
        rbp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbpActionPerformed(evt);
            }
        });
        getContentPane().add(rbp);
        rbp.setBounds(180, 190, 90, 23);

        bg.add(rbl);
        rbl.setText("Laki-laki");
        rbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblActionPerformed(evt);
            }
        });
        getContentPane().add(rbl);
        rbl.setBounds(290, 190, 110, 23);

        jLabel6.setText("Kg");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(250, 150, 30, 30);

        jLabel7.setText("Cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 110, 30, 30);

        bkeluar.setBackground(new java.awt.Color(51, 255, 255));
        bkeluar.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar);
        bkeluar.setBounds(350, 240, 90, 30);

        bhitung.setBackground(new java.awt.Color(51, 255, 255));
        bhitung.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        bhitung.setText("Hitung");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        getContentPane().add(bhitung);
        bhitung.setBounds(60, 240, 80, 30);

        bcl.setBackground(new java.awt.Color(51, 255, 255));
        bcl.setFont(new java.awt.Font("Sylfaen", 0, 12)); // NOI18N
        bcl.setText("Coba Lagi");
        bcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclActionPerformed(evt);
            }
        });
        getContentPane().add(bcl);
        bcl.setBounds(190, 240, 110, 30);

        jLabel8.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel8.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 300, 180, 30);
        getContentPane().add(ideal);
        ideal.setBounds(250, 300, 60, 30);

        jLabel9.setText("Kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 300, 30, 30);
        getContentPane().add(saran);
        saran.setBounds(60, 440, 400, 40);
        getContentPane().add(hasil);
        hasil.setBounds(60, 390, 400, 40);

        jLabel11.setFont(new java.awt.Font("Sitka Heading", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 340, 200, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16374126-Splash-vector-background-cover-template--Stock-Vector-background-colorful-abstract.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 510, 520);

        setBounds(0, 0, 517, 556);
    }// </editor-fold>//GEN-END:initComponents

    private void tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        if(bb.getText().equals("") || tinggi.getText().equals("") || nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak Isian belum diisi, mohon dilengkapi");
        } else if (rbp.isSelected() || rbl.isSelected()) {
            try {
                Proses();
            }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
        }} else {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin silahkan dipilih");
        }
    }//GEN-LAST:event_bhitungActionPerformed

    private void rbpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbpActionPerformed

    private void rblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        //dispose();
        System.exit(0);
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        tinggi.setText("");
        bb.setText("");
        bg.clearSelection();
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
    }//GEN-LAST:event_bclActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.JButton bcl;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton bhitung;
    private javax.swing.JButton bkeluar;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton rbl;
    private javax.swing.JRadioButton rbp;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tinggi.getText());
        bt = Double.valueOf(bb.getText());
        
        if (rbp.isSelected()) {
            h1 = (ti - 110 ) * 1;
        } else {
            h1 = (ti - 104 ) * 1;
        } temp = Double.toString(h1.intValue());
        
        if (h1 < bt ) {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText()+ " , Sepertinya anda Overweight :( ");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if (h1 > bt) {
            ideal.setText(temp);
            hasil.setText("Maaf " + nama.getText()+ " , Sepertinya anda Underweight : ( ");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");        
        } else {
            ideal.setText(temp);
            hasil.setText("Hallo" + nama.getText()+ " , Berat Badan Anda sudah ideal : ( ");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
        }
    }
}
